language: node_js
cache: yarn
node_js:
  - stable
  - "6"
notifications:
  email:
    - olegaleshkin@gmail.com
    - me@aleshaoleg.me
  on_success: never
  on_failure: always
after_success: 'npm run coveralls'
