before_install:
- npm install -g yarn@latest
- npm install -g greenkeeper-lockfile
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
language: node_js
cache: yarn
node_js:
  - stable
notifications:
  email:
    - olegaleshkin@gmail.com
  on_success: never
  on_failure: always
after_success: 'npm run coveralls'
